export enum FailureReason {
  UNABLE_TO_COMPLETE_TRANSACTION = 'UNABLE_TO_COMPLETE_TRANSACTION',
  INVALID_PAYMENT_METHOD = 'INVALID_PAYMENT_METHOD',
  PAYER_CANNOT_PAY = 'PAYER_CANNOT_PAY',
  CANNOT_PAY_THIS_PAYEE = 'CANNOT_PAY_THIS_PAYEE',
  REDIRECT_REQUIRED = 'REDIRECT_REQUIRED',
  PAYEE_FILTER_RESTRICTIONS = 'PAYEE_FILTER_RESTRICTIONS',
}
